version: "3"
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    restart: always

  database:
    image: postgres:9.6.24-alpine3.15
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
